### ISSUE TITLE
Constant Crashing

### ISSUE THREAD

**Issue by AAA12702** [LinuxndroidTeam/DroidSpy2#3]
Tested on Android 12 & 13. App works but constantly crashes within minutes of startup. Issue possibly lies in clipboard extraction.

**Comment by LinuxndroidTeam** [comment]
in Chinese phone required Autostart permission so make sure allow it when launch app.

**Comment by AAA12702** [comment]
No, these were not Chinese phones, USA. Also, all permissions were granted. Issue should not have been closed.
