### ISSUE TITLE
SCAM   THIS DOES NOTHING EXCEPT INFECT YOUR COMPUTER WITH MALWARE

### ISSUE THREAD

**Issue by ShadyTrapShit** [LinuxndroidTeam/DroidSpy2#5]

**Comment by LinuxndroidTeam** [comment]
hi dear please share any proof, and do reverse engineering.  do not such thing without proof. 

that's why it's detect because Defender Flag Android Spyware file, So I Already tell and recommend to you install in RDP, VM
